language: objective-c
osx_image: xcode7.3

cache:
  directories:
    - Carthage

before_install:
  - brew update 

install:
  - carthage bootstrap --platform ios --no-use-binaries

script:
  - set -o pipefail
  - xcodebuild test -project Qiita-client.xcodeproj -scheme Qiita-client -sdk iphonesimulator | xcpretty -c
